### ISSUE TITLE
Unsupported platform: Windows_NT x64

### ISSUE THREAD

**Issue by coolsnake** [near/sandbox#36]
I want to install sandbox in windows 10 and got following error:

$ npm i -g near-sandbox
npm ERR! code 1
npm ERR! path d:\nodejs\node_global\node_modules\near-sandbox
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node ./install.js
npm ERR! d:\nodejs\node_global\node_modules\near-sandbox\dist\getBinary.js:13
npm ERR!     throw new Error(`Unsupported platform: ${type} ${arch}`);
npm ERR!     ^
npm ERR!
npm ERR! Error: Unsupported platform: Windows_NT x64
npm ERR!     at getPlatform (d:\nodejs\node_global\node_modules\near-sandbox\dist\getBinary.js:13:11)
npm ERR!     at AWSUrl (d:\nodejs\node_global\node_modules\near-sandbox\dist\getBinary.js:16:30)
npm ERR!     at getBinary (d:\nodejs\node_global\node_modules\near-sandbox\dist\getBinary.js:27:19)
npm ERR!     at Object.<anonymous> (d:\nodejs\node_global\node_modules\near-sandbox\dist\install.js:4:27)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1105:14)
npm ERR!     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:981:32)
npm ERR!     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
npm ERR!     at Module.require (node:internal/modules/cjs/loader:1005:19)
npm ERR!     at require (node:internal/modules/cjs/helpers:102:18)

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\nodejs\node_cache\_logs\2022-05-18T09_18_38_662Z-debug-0.log

**Comment by TMadzi** [comment]
Any update or workaround on this? I am facing the same issue.

**Comment by willemneal** [comment]
I would try using the linux subsystem.  The architecture is supported, just not the OS.

**Comment by rmuftiev** [comment]
Hey! We are facing the same issue. Any updates?

**Comment by volovyks** [comment]
@ChaoticTempest how big is the effort to fix this? It is blocking https://github.com/near/near-sdk-js/issues/94.
And is it on our roadmap?

**Comment by ChaoticTempest** [comment]
@volovyks nothing planned in our roadmap. The big issue with supporting windows is that windows hasn't been tested that well on nearcore, so there can be unexpected behavior if we publish those binaries. Would probably require another separate pipeline specifically for those as well similarly to when the M1 one was added.

So unfortunately, it's recommended for users to use WSL2 when going to test
