### ISSUE TITLE
Unable to deploy contract to sandbox due to write EPIPE error

### ISSUE THREAD

**Issue by veigajoao** [near/sandbox#37]
When running a simple contract deploy using near-api.js I'm running into the following error:

```
 Retrying HTTP request for http://localhost:3030 because of error: FetchError: request to http://localhost:3030/ failed, reason: write EPIPE
```

After a while the test exits with the following message:
```
PayloadTooLargeError: Json payload size is bigger than allowed
```

In order to solve the problem I tried changing the config.json for the sandbox:
```
"rpc": {
    "addr": "0.0.0.0:3030",
    "prometheus_addr": null,
    "cors_allowed_origins": [
      "*"
    ],
    "polling_config": {
      "polling_interval": {
        "secs": 0,
        "nanos": 500000000
      },
      "polling_timeout": {
        "secs": 10,
        "nanos": 0
      }
    },
    "limits_config": {
      "json_payload_max_size": 10485760000000000000 // was previously 10485760
    },
    "enable_debug_rpc": false
  },
```

After that the tests stoped exiting with the error code. Instead they started to hang, displaying the following messages (an infinite retrying of the transaction):
```
Retrying transaction 1a3c1a37-f7de-49f1-8927-1f640de62a8a.test.near:7d3pP5Md6PdqLu3LybuFidwgva8hSk7ZAsNEcmpoHEPb due to expired block hash

      at Object.logWarning (../../node_modules/near-api-js/lib/utils/errors.js:32:17)
      at ../../node_modules/near-api-js/lib/account.js:130:30
      at Object.exponentialBackoff [as default] (../../node_modules/near-api-js/lib/utils/exponential-backoff.js:7:24)
      at Account.signAndSendTransactionV2 (../../node_modules/near-api-js/lib/account.js:117:24)

  console.warn
    Retrying HTTP request for http://localhost:3030 because of error: FetchError: request to http://localhost:3030/ failed, reason: write EPIPE

      at Object.logWarning (../../node_modules/near-api-js/lib/utils/errors.js:32:17)
      at ../../node_modules/near-api-js/lib/utils/web.js:40:26
      at Object.exponentialBackoff [as default] (../../node_modules/near-api-js/lib/utils/exponential-backoff.js:7:24)
      at Object.fetchJson (../../node_modules/near-api-js/lib/utils/web.js:22:22)
      at ../../node_modules/near-api-js/lib/providers/json-rpc-provider.js:312:34
      at Object.exponentialBackoff [as default] (../../node_modules/near-api-js/lib/utils/exponential-backoff.js:7:24)

  console.warn
    Retrying transaction 1a3c1a37-f7de-49f1-8927-1f640de62a8a.test.near:2kK63vFtuUFMeXzxhhe8SZ88VCjmn2amkUN8F8ew2ky2 due to expired block hash
...
```

The transactions all run normally in testnet.

I'm sharing the test file in full: 
```
/* eslint-disable @typescript-eslint/no-empty-function */
import { Account, Contract, Near } from "near-api-js";
import { Staking } from "../lib/staking";
import { deployContract } from "./utils";
import { TokenContract } from "@near/ts";
import { setupNearWithContractAccounts } from "./utils/accounts";

import fs from "fs";
import path from "path";

const yield_per_period = "10";
const period_duration = "604800000";

describe("Staking Contract", () => {
  let masterAccount: Account;
  let account: Account;
  let tokenContractAccount: Account;
  let stakingContractAccount: Account;
  let near: Near;
  let config: any;
  let stakingContract: Staking;
  let tokenContract: TokenContract;

  beforeAll(async () => {
    const { testAccount, tokenAccount, stakingAccount, near, ...rest } =
      await setupNearWithContractAccounts();
    masterAccount = rest.masterAccount;

    tokenContractAccount = tokenAccount;
    stakingContractAccount = stakingAccount;

    account = testAccount;
    config = rest.config;

    // BOTH DEPLOYS PRESENT THE SAME ISSUE
    await stakingContractAccount.deployContract(fs.readFileSync(path.resolve(__dirname, '../out/staking.wasm')));
    await tokenContractAccount.deployContract(fs.readFileSync(path.resolve(__dirname, '../out/token_contract.wasm')));

  });

  it("should stake some balance into the user account", () => {
    expect(true).toBe(true);
  });
});

```

Also sharing the issue repo: https://github.com/hack-a-chain-software/jump.project/tree/issue/integration-testnet-failing

Environment:
Ubuntu 20.04

Is there any configuration that I'm missing?

**Comment by willemneal** [comment]
The link you shared is to a private repo.  How big are the contracts?

**Comment by veigajoao** [comment]
My fault guys, I was passing the --debug flag in the compile script. That caused the file to be too large and the node did not accept it.

Closing the issue
