### ISSUE TITLE
Error while importing \"env\".\"promise_batch_action_function_call_weight\": unknown import.

### ISSUE THREAD

**Issue by fadeevab** [near/sandbox#53]
There is an error executing smart contracts compiled with the official `4.0.0` `near-sdk-rs`.

```
"wasm execution failed with error: FunctionCallError(LinkError { msg: \"Error while importing \\\"env\\\".\\\"promise_batch_action_function_call_weight\\\": unknown import. Expected Function(FunctionType { params: [I64, I64, I64, I64, I64, I64, I64, I64], results: [] })\" })",
```

It only works with the following dependency specification:
```toml
[dependencies]
near-contract-standards = "=4.0.0-pre.7"
near-sdk = {version = "=4.0.0-pre.7", features = ["unstable"]}
```

`4.0.0-pre.8` does not work.
Also, the error reproduces without `features = ["unstable"]`.

*Example:*
```bash
$ near view test.near version $SANDBOX
```
*Full error log:*
```
View call: test.near.version()
Loaded master account test.near key from /tmp/near-cc-sandbox/validator_key.json with public key = ed25519:FC9raLTzGt34uiANkKRGkhD9hZrLXz5HxUGJCxF3f6iG
An error occured
Error: Querying [object Object] failed: wasm execution failed with error: FunctionCallError(LinkError { msg: "Error while importing \"env\".\"promise_batch_action_function_call_weight\": unknown import. Expected Function(FunctionType { params: [I64, I64, I64, I64, I64, I64, I64, I64], results: [] })" }).
{
  "block_hash": "BQva5tDv2khhDvMroHVAtUib7xvRRtnhLCDQpjG6vXfq",
  "block_height": 1795,
  "error": "wasm execution failed with error: FunctionCallError(LinkError { msg: \"Error while importing \\\"env\\\".\\\"promise_batch_action_function_call_weight\\\": unknown import. Expected Function(FunctionType { params: [I64, I64, I64, I64, I64, I64, I64, I64], results: [] })\" })",
  "logs": []
}
    at JsonRpcProvider.query (/home/user/.nvm/versions/node/v16.16.0/lib/node_modules/near-cli/node_modules/near-api-js/lib/providers/json-rpc-provider.js:123:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Account.viewFunction (/home/user/.nvm/versions/node/v16.16.0/lib/node_modules/near-cli/node_modules/near-api-js/lib/account.js:366:24)
    at async exports.callViewFunction (/home/user/.nvm/versions/node/v16.16.0/lib/node_modules/near-cli/index.js:103:48)
    at async Object.handler (/home/user/.nvm/versions/node/v16.16.0/lib/node_modules/near-cli/utils/exit-on-error.js:52:9)
TypedError: Querying [object Object] failed: wasm execution failed with error: FunctionCallError(LinkError { msg: "Error while importing \"env\".\"promise_batch_action_function_call_weight\": unknown import. Expected Function(FunctionType { params: [I64, I64, I64, I64, I64, I64, I64, I64], results: [] })" }).
{
  "block_hash": "BQva5tDv2khhDvMroHVAtUib7xvRRtnhLCDQpjG6vXfq",
  "block_height": 1795,
  "error": "wasm execution failed with error: FunctionCallError(LinkError { msg: \"Error while importing \\\"env\\\".\\\"promise_batch_action_function_call_weight\\\": unknown import. Expected Function(FunctionType { params: [I64, I64, I64, I64, I64, I64, I64, I64], results: [] })\" })",
  "logs": []
}
    at JsonRpcProvider.query (/home/user/.nvm/versions/node/v16.16.0/lib/node_modules/near-cli/node_modules/near-api-js/lib/providers/json-rpc-provider.js:123:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Account.viewFunction (/home/user/.nvm/versions/node/v16.16.0/lib/node_modules/near-cli/node_modules/near-api-js/lib/account.js:366:24)
    at async exports.callViewFunction (/home/user/.nvm/versions/node/v16.16.0/lib/node_modules/near-cli/index.js:103:48)
    at async Object.handler (/home/user/.nvm/versions/node/v16.16.0/lib/node_modules/near-cli/utils/exit-on-error.js:52:9) {
  type: 'UntypedError',
  context: undefined
}
```

**Comment by fadeevab** [comment]
As I understand, the SDK v4.0.0 injects `promise_batch_action_function_call_weight` function call into a contract while sandbox host doesn't introduce such function.

**Comment by fadeevab** [comment]
@ChaoticTempest @willemneal Could you take a loot at it? Thanks!

**Comment by fadeevab** [comment]
All right, thanks, bumping the version works:

```json
    "devDependencies": {
        "near-sandbox": "0.0.15"
    }
```

The new near node requires 11000 `ulimit -n` though, which is another story.
